version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: blog
      MYSQL_USER: nathan
      MYSQL_PASSWORD: jesuisnathan
    networks:
      - networks_BDD

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my_phpmyadmin
    environment:
      PMA_HOST: my_mysql
    ports:
      - "8080:80"
    networks:
      - networks_BDD

networks:
  networks_BDD:
    driver: bridge
